[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --no-migrations

markers =
    unit: marks tests as unit tests
    integration: marks tests as integration tests
    regression: marks tests as regression tests
    performance: marks tests as performance/load tests
    system: marks tests as system tests

# Configurar o acesso ao banco de dados por padrão para todos os testes
# As configurações abaixo foram removidas/atualizadas para evitar warnings
# django_db_setup = True
# django_db_use_migrations = False
# django_db_keepdb = True 